### ISSUE TITLE
Suggestion about missing beat/beat-type; I think it should default to 4/4

### ISSUE THREAD

**Issue by deepio** [cuthbertLab/music21#462] opened 2019-10-29 16:09 UTC
Valid musicxml files do not need to write beats or beat-type
I don't believe `Finale v26 for Mac` encodes this when all is in 4/4. Finale actually outputs this:
```xml
      <attributes>
        <divisions>4</divisions>
        <key>
          <fifths>-2</fifths>
          <mode>major</mode>
        </key>
        <clef>
          <sign>G</sign>
          <line>2</line>
        </clef>
      </attributes>
```
```xml
   <attributes>
    <divisions>256</divisions>
    <key color="#000000">
     <fifths>-2</fifths>
     <mode>major</mode>
    </key>
    <time color="#000000">
     <beats>4</beats>
     <beat-type>4</beat-type>
    </time>
    <staves>1</staves>
    <clef number="1" color="#000000">
     <sign>G</sign>
     <line>2</line>
    </clef>
    <staff-details number="1" print-object="yes" />
   </attributes>
```
I think it would be better to default to 4/4 in these cases when beats and beat-type is omitted, or double what was in the previous measure.

**Comment by mscuthbert** [comment] 2019-10-29 16:20
Sorry -- I need more context.  What is Finale's output, what is music21 doing, what do you think music21 should do, and why should it do this?  Thanks

**Comment by deepio** [comment] 2019-10-29 16:30
Sorry -- Finale produces musicxml that does not specify the time signature. When using 
`music21.converter.parseFile(filepath).recurse().getElementsByClass("Part")` to create isolated parts and for each part `parts.recurse().getElementsByClass("TimeSignature")` we get an empty list on the finale file that does not specify beats or beat-type. But in a file that does have those attributes (created with sibelius 7+, musescore, dorico), we get a list of all the time signatures.

If I wanted to compare two musicxml files that are created with different software, the finale one will have more errors because all the time signatures are wrong.

**Comment by mscuthbert** [comment] 2019-10-29 16:36
When producing software does not specify an element like a time signature, music21's default is to not supply one -- this is by design.  We also don't specify an instrument, a key, etc., if these are not given.  In a solution where music21 automatically supplies a time signature, how would a user of music21 know that no time signature was given in the source score?  

Finale 26 for Mac produces a time signature for me:

![Screen Shot 2019-10-29 at 12 35 20](https://user-images.githubusercontent.com/3521479/67788368-92dc2100-fa48-11e9-8776-d8412895bd40.png)
<img width="128" alt="Screen Shot 2019-10-29 at 12 35 30" src="https://user-images.githubusercontent.com/3521479/67788386-996a9880-fa48-11e9-9a67-4d2da5c3ff9a.png">

Since it would be easy to add a time signature if one is missing but hard to remove them if none was provided, I think that this is likely to be a `wontfix`.

**Comment by deepio** [comment] 2019-10-29 16:58
Why would a user not want to know what key a file was meant to be in when it's omitted (because of, for example, C major), or time signature (4/4)? If someone is using music21 to parse a file would they not want to know all the information about how it would be rendered in a traditional viewer?

That actually underscores another issue i've been having with Finale and music21. For some reason, it can't read compressed musicxml files. 
```python
File "/Users/alex/Documents/GitHub/gandalf/env/lib/python3.7/site-packages/music21/converter/__init__.py", line 1009, in parseFile
    v.parseFile(fp, number=number, format=format, forceSource=forceSource, **keywords)
  File "/Users/alex/Documents/GitHub/gandalf/env/lib/python3.7/site-packages/music21/converter/__init__.py", line 544, in parseFile
    self.parseFileNoPickle(fp, number, format, forceSource, **keywords)
  File "/Users/alex/Documents/GitHub/gandalf/env/lib/python3.7/site-packages/music21/converter/__init__.py", line 478, in parseFileNoPickle
    self.subConverter.parseFile(fp, number=number, **keywords)
  File "/Users/alex/Documents/GitHub/gandalf/env/lib/python3.7/site-packages/music21/converter/subConverters.py", line 843, in parseFile
    c.parseXMLText()
  File "/Users/alex/Documents/GitHub/gandalf/env/lib/python3.7/site-packages/music21/musicxml/xmlToM21.py", line 845, in parseXMLText
    self.xmlRoot = ET.XML(self.xmlText)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
TypeError: a bytes-like object is required, not 'NoneType'
```
So I unzipped it, and opened the xml file inside with music21 and the beat/beat-types where missing. Maybe there is a difference when you export between compressed and uncompressed. I can give you the file if you like to see for yourself.

**Comment by mscuthbert** [comment] 2019-10-29 17:20
The compressed XML I get from Finale also has the time signature.

I don't think you have a full grasp of the range of features people use music21 for -- non-Western music, contemporary scores, medieval music.  For all of which it would be incorrect to add a time signature of 4/4 or a key signature of C major in case none was specified.  Have your program check for the absence of these features and add them if they're missing.

Re: Reading Compressed XML -- I think if you have a second problem make it a second issue.  I haven't seen this one and it's a fundamental thing people use music21 for.

**Closed** 2019-10-29 22:23 UTC
