### ISSUE TITLE
Dominant of C != Dominant of c

### ISSUE THREAD

**Issue by napulen** [cuthbertLab/music21#700] opened 2020-12-06 04:59 UTC
**music21 version**

`6.3.0`   

**Problem summary**

As I was playing with some roman numeral chords, I noticed that many chords that I expected to be "the same", were actually not.

**Steps to reproduce**

Here is an example:

```python
In [1]: import music21

In [2]: c1 = music21.roman.RomanNumeral('V', 'C')

In [3]: c2 = music21.roman.RomanNumeral('V', 'c')

In [4]: c1.pitches == c2.pitches
Out[4]: False

In [5]: [(c1[i] == c2[i]) for i in range(3)]
Out[5]: [True, False, True]
```

It seems that the leading tone (in this case) is what is different. Not sure if this is expected (a deliberate difference in tuning) or a bug. 

I'd expect chords to be identical as long as their pitches were identical.

**Comment by mscuthbert** [comment] 2020-12-06 08:06
what are the actual pitches for each?   What is the thing that is different?

**Comment by mscuthbert** [comment] 2020-12-06 08:07
In fact, they're not the same.  The leading tone is a B in C major and a B with an explicit natural sign in c minor.  They don't compare identically; by design.  Closing -- reopen if this isn't the case.

**Closed by mscuthbert** 2020-12-06 08:07 UTC
