### ISSUE TITLE
Ties in Chords Missing After Write Stream to MIDI and Read Back

### ISSUE THREAD

**Issue by myersjm** [cuthbertLab/music21#775] opened 2021-01-13 22:50 UTC
**music21 version**

`9.8.7`   

**Problem summary**

I am working on a large project involving constructing streams and then writing them to file as MIDI. I am constructing chords with notes where some of the notes are tied and others aren't. In my larger code, notes that are not tied are disappearing when I read back the MIDI from file. I tried to replicate this in a simpler context, but could not reproduce the exact behavior. But the simpler code is not doing what I expect, either. The ties present before writing to file are correct, but when I read back the file, the stream's chords do not have the ties anymore. This could be either a user error or an actual bug. Any help would be much appreciated!

**Steps to reproduce**

```
n0 = note.Note("C4")
n0.tie = tie.Tie('start')

n1 = note.Note("C4")
n2 = note.Note("F4")
n1.tie = tie.Tie('continue')

n3 = note.Note("C4")
n4 = note.Note("F4")
n3.tie = tie.Tie('stop')

note_arr0 = [n0]
note_arr = [n1, n2]
note_arr2 = [n3, n4]
c0 = chord.Chord(note_arr0)
c1 = chord.Chord(note_arr)
c2 = chord.Chord(note_arr2)

s = stream.Stream()
s.append(c0)
s.append(c1)
s.append(c2)
s.show()

# Then I read back the stream, and the ties are now gone:

fp = s.write('midi', fp='./Data/why.mid')
path = 'C:/Users/myersjm/Documents/11 Senior Year/Senior Thesis/Data/why.mid'

score = converter.parse(path)
score.show()

```

**Expected vs. actual behavior**

Before writing, the ties are correct and present in the stream:
![Before_Write](https://user-images.githubusercontent.com/31910744/104517669-746a3300-55c4-11eb-8df4-f1040043b28d.PNG)
After I write to file and read it back, the stream does not have any ties anymore, which is an issue, as it should be identical to before:
![After_Write](https://user-images.githubusercontent.com/31910744/104517667-73d19c80-55c4-11eb-8916-0a4f106efa0d.PNG)

**More information**

My main question is, am I using the ties correctly? If so, are there some underlying things that happen when you write a stream to MIDI and read it back where some of the tie information, or note information, is lost? My original issue was that some notes are disappearing in chords after I write them to file, but I am thinking this could be tied to an issue with how I am using ties. Thanks for any help! I am using Windows 10, if that is useful information, by the way.

**Comment by jacobtylerwalls** [comment] 2021-01-13 23:19
Hi, and thanks for the report. This is discussed in #620, i.e. the current behavior of re-attacking every member of a partially-tied chord when exporting MIDI.

#620 discusses an approach of someday creating voices from partially-tied chords before exporting to MIDI. If you have any success implementing this yourself, do drop by here or the mailing list--I myself would be glad to hear about it!

You may find a benefit to exporting musicxml instead and relying on another package or tool to convert to MIDI if you need partially-tied chords to roundtrip to and from MIDI correctly.

Finally, do you have advice about where we could add clarification about this behavior in the documentation to make it more discoverable? Cheers, Jacob

**Comment by mscuthbert** [comment] 2021-01-14 01:31
Closing as duplicate of #620  -- let's continue the discussion there!  :-)

**Closed by mscuthbert** 2021-01-14 01:31 UTC
