### ISSUE TITLE
Unable to detect undefined names

### ISSUE THREAD

**Issue by syntheso** [cuthbertLab/music21#452] opened 2019-10-11 13:55 UTC
Yesterday everything was working fine with music21 in Spyder IDE, now I get this error before I run the following line:

`from music21 import *`

If I run the line I get:

`AttributeError: module 'music21' has no attribute 'pitch'`

I updated to see if that resolved it, but it doesn't.

**Comment by syntheso** [comment] 2019-10-11 15:27
I uninstalled and reinstalled and working now, although I still get the same warning (which I think you mention in your documentation anyway). Hoping I won't need to do the same again! Thanks.

**Comment by syntheso** [comment] 2019-10-11 15:45
Actually, no, just restarted Spyder.. not working again.

**Comment by mscuthbert** [comment] 2019-10-11 17:33
Does it work outside of Spyder IDE?  If so then the problem isn't in music21 I'm afraid.

**Comment by mscuthbert** [comment] 2019-10-26 18:19
Closing -- feel free to reopen if the problem exists outside of SpyderIDE, but pitch not being found would be a pretty fundamental music21 error that others would have encountered.

**Closed by mscuthbert** 2019-10-26 18:19 UTC
