### ISSUE TITLE
AttributeError when writing mxl to midi

### ISSUE THREAD

**Issue by malcolmsailor** [cuthbertLab/music21#1186] opened 2021-12-15 12:36 UTC
**music21 version**

7.1.0

**Problem summary**

`AttributeError: 'Rest' object has no attribute 'pitches'` is raised when attempting to write an `mxl` file from the When-in-Rome corpus to midi.  NB the file appears to open correctly in Musescore.

**Steps to reproduce**

Here I use the path to the local file on my machine.

```
import music21

path = "/Users/malcolm/datasets/When-in-Rome/Corpus/Etudes_and_Preludes/Bach,_Johann_Sebastian/The_Well-Tempered_Clavier_I/10/score.mxl"

score = music21.converter.parse(path, format="musicxml")
score.write("midi", "temp.mid")
```

NB if I try to use the Github URL to the file, as below, I get a different exception, `xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2`. I presume this is because I am using the wrong URL or something like that.

```
import music21

music21.environment.UserSettings()["autoDownload"] = "allow"

url = "https://github.com/MarkGotham/When-in-Rome/blob/master/Corpus/Etudes_and_Preludes/Bach,_Johann_Sebastian/The_Well-Tempered_Clavier_I/10/score.mxl?raw=true"

score = music21.converter.parse(url, format="musicxml")
score.write("midi", "temp.mid")
```

**Expected vs. actual behavior**

**More information**

Here's the full traceback:

```
Traceback (most recent call last):
  File "/Users/malcolm/Dropbox/data_science/roman_numerals/music21_bug.py", line 26, in <module>
    score.write("midi", "temp.mid")
  File "/Users/malcolm/venvs/roman_numerals/lib/python3.9/site-packages/music21/stream/base.py", line 328, in write
    return super().write(fmt=fmt, fp=fp, **keywords)
  File "/Users/malcolm/venvs/roman_numerals/lib/python3.9/site-packages/music21/base.py", line 2665, in write
    return formatWriter.write(self,
  File "/Users/malcolm/venvs/roman_numerals/lib/python3.9/site-packages/music21/converter/subConverters.py", line 1147, in write
    mf = midiTranslate.music21ObjectToMidiFile(obj, **midiTranslateKeywords)
  File "/Users/malcolm/venvs/roman_numerals/lib/python3.9/site-packages/music21/midi/translate.py", line 260, in music21ObjectToMidiFile
    return streamToMidiFile(music21Object, addStartDelay=addStartDelay)
  File "/Users/malcolm/venvs/roman_numerals/lib/python3.9/site-packages/music21/midi/translate.py", line 2559, in streamToMidiFile
    midiTracks = streamHierarchyToMidiTracks(s,
  File "/Users/malcolm/venvs/roman_numerals/lib/python3.9/site-packages/music21/midi/translate.py", line 2443, in streamHierarchyToMidiTracks
    subs.stripTies(inPlace=True, matchByPitch=False)
  File "/Users/malcolm/venvs/roman_numerals/lib/python3.9/site-packages/music21/stream/base.py", line 7268, in stripTies
    if nLast and (len(nLast.pitches) != len(n.pitches)):
AttributeError: 'Rest' object has no attribute 'pitches'
```

**Comment by jacobtylerwalls** [comment] 2021-12-15 13:47
Duplicate of #1161. Fixed in master, which you can treat as a pre-release and install using pip with a github URL. I would hope we can put a maintenance release out over the winter.

**Comment by jacobtylerwalls** [comment] 2021-12-15 13:48
A workaround is described here: https://github.com/cuthbertLab/music21/issues/1161#issuecomment-959779645

**Closed by jacobtylerwalls** 2021-12-15 13:47 UTC
