### ISSUE TITLE
Failing to merge certain humdrum "split-voice" spines

### ISSUE THREAD

**Issue by napulen** [cuthbertLab/music21#884] opened 2021-03-03 21:46 UTC
`6.7.1`   

**Problem summary**

After merging split Humdrum spines, the music21 Humdrum parser fails to create a valid representation. It seems to be associated with multiple voices joining at once, because splitting and merging a single voice works without issues. 

**Steps to reproduce**

```python
test = """
**kern	**kern
*part1	*part1
*staff2	*staff1
*I"Piano	*
*I'Pno.	*
*clefF4	*clefG2
*k[f#c#g#]	*k[f#c#g#]
*M2/4	*M2/4
=1	=1
2r	2r
=2	=2
*^	*
*	*^	*
*	*	*^	*
4.r	4r	8r	[2D#X\	2r
.	.	[4.F#/	.	.
.	[4A	.	.	.
8B	.	.	.	.
*v	*v	*v	*v	*
=3	=3
2D#_ 2F#_ 2A_ [2cn	8d#XL
.	8f#J
.	8aL
.	8bJ
=4	=4
2D#] 2F#] 2A] 2c]	2ccn
==	==
*-	*-
!!!system-decoration: {(s1,s2)}
"""


import music21
s = music21.converter.parse(test)
s.show()
```

**Expected vs. actual behavior**

The example was encoded in MuseScore and converted using Verovio Humdrum Viewer.

Expectation
![image](https://user-images.githubusercontent.com/7258463/109876189-786b1680-7c3f-11eb-893d-4f28ec939719.png)

Result (after parsing and running `.show()`)
![image](https://user-images.githubusercontent.com/7258463/109876236-8d47aa00-7c3f-11eb-86fe-5332bdd0d42c.png)

I've found several instances of this behavior across Humdrum files. In all cases, there are ties involved, and there are multiple voices merging at once. Any example with that combination will probably reproduce the issue.

**Comment by jacobtylerwalls** [comment] 2021-03-04 01:16
Greetings, Néstor. I see this when I try to parse your example on 6.7.1 (just as on the dev version):

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwalls/music21/music21/converter/__init__.py", line 1184, in parse
    return parseData(value, number=number, format=m21Format, **keywords)
  File "/Users/jwalls/music21/music21/converter/__init__.py", line 1038, in parseData
    v.parseData(dataStr, number=number, format=format, **keywords)
  File "/Users/jwalls/music21/music21/converter/__init__.py", line 631, in parseData
    self.subConverter.parseData(dataStr, number=number)
  File "/Users/jwalls/music21/music21/converter/subConverters.py", line 673, in parseData
    hdf.parse()
  File "/Users/jwalls/music21/music21/humdrum/spineParser.py", line 170, in parse
    return self.parseNonOpus(dataStream)
  File "/Users/jwalls/music21/music21/humdrum/spineParser.py", line 190, in parseNonOpus
    self.spineCollection.createMusic21Streams()
  File "/Users/jwalls/music21/music21/humdrum/spineParser.py", line 1722, in createMusic21Streams
    self.reclassSpines()
  File "/Users/jwalls/music21/music21/humdrum/spineParser.py", line 1850, in reclassSpines
    if thisSpine.spineType == 'kern':
  File "/Users/jwalls/music21/music21/humdrum/spineParser.py", line 1149, in _getSpineType
    raise HumdrumException('Could not determine spineType '
music21.humdrum.spineParser.HumdrumException: Could not determine spineType for spine with id 1
```

Is there something missing from your example?

**Comment by napulen** [comment] 2021-03-04 16:49
Hey Jacob :).

Ok, so I am positioning the script within the latest commit of the `master` branch. That'd be commit `ef4bdd6ae787ffb189486a126e6f1a2ee0b556c7`.

Running the same code excerpt, but adding a `print(music21.__version__)` to it. It throws `7.0.0` as the version and this score:

![image](https://user-images.githubusercontent.com/7258463/109998390-2d084500-7cdf-11eb-83f4-22bf1ddffcb0.png)

Weird that you are getting a crash on the humdrum parser and I am not. I am running on Linux, but I don't think Linux or MuseScore's version would have something to do with the humdrum spine parser.

**Comment by napulen** [comment] 2021-03-04 16:52
Question: Have you copy-pasted the code I shared into an editor that could be doing tab2space replacement? More often than not, my errors with Humdrum have something to do with tabs.

**Comment by napulen** [comment] 2021-03-04 16:53
Thank you for looking into this so quickly, by the way.

**Comment by jacobtylerwalls** [comment] 2021-03-04 16:56
Thanks, that was it -- pasting into a terminal window from Github didn't preserve tabs.

**Comment by jacobtylerwalls** [comment] 2021-03-04 17:06
Sure, all I wanted to do was just grab the text dump. As you know, voices are one of the pain points of the system:

```
>>> s.show('t', addEndTimes=True)
{0.0 - 0.0} <music21.metadata.Metadata object at 0x102c0d490>
{0.0 - 4.0} <music21.stream.Part spine_1>
    {0.0 - 0.0} <music21.humdrum.spineParser.MiscTandem **kern>
    {0.0 - 0.0} <music21.humdrum.spineParser.MiscTandem *part1>
    {0.0 - 0.0} <music21.humdrum.spineParser.MiscTandem *staff1>
    {0.0 - 2.0} <music21.stream.Measure 1 offset=0.0>
        {0.0 - 0.0} <music21.clef.TrebleClef>
        {0.0 - 0.0} <music21.key.KeySignature of 3 sharps>
        {0.0 - 0.0} <music21.meter.TimeSignature 2/4>
        {0.0 - 2.0} <music21.note.Rest rest>
        {2.0 - 2.0} <music21.bar.Barline type=regular>
    {2.0 - 4.0} <music21.stream.Measure 2 offset=2.0>
        {0.0 - 2.0} <music21.note.Rest rest>
{0.0 - 6.0} <music21.stream.Part spine_0>
    {0.0 - 0.0} <music21.humdrum.spineParser.MiscTandem **kern>
    {0.0 - 0.0} <music21.humdrum.spineParser.MiscTandem *part1>
    {0.0 - 0.0} <music21.humdrum.spineParser.MiscTandem *staff2>
    {0.0 - 0.0} <music21.humdrum.spineParser.MiscTandem "Piano>
    {0.0 - 0.0} <music21.humdrum.spineParser.MiscTandem 'Pno.>
    {0.0 - 2.0} <music21.stream.Measure 1 offset=0.0>
        {0.0 - 0.0} <music21.clef.BassClef>
        {0.0 - 0.0} <music21.key.KeySignature of 3 sharps>
        {0.0 - 0.0} <music21.meter.TimeSignature 2/4>
        {0.0 - 2.0} <music21.note.Rest rest>
        {2.0 - 2.0} <music21.bar.Barline type=regular>
    {2.0 - 6.0} <music21.stream.Measure 2 offset=2.0>
        {0.0 - 2.0} <music21.stream.Voice 0x102bd6880>
            {0.0 - 1.5} <music21.note.Rest rest>
            {1.5 - 2.0} <music21.note.Note B>
        {0.0 - 4.0} <music21.stream.Voice 0x102bd64f0>
            {0.0 - 2.0} <music21.chord.Chord D#3 F#3 A3 C4>
            {2.0 - 4.0} <music21.chord.Chord D#3 F#3 A3 C4>
{0.0 - 0.0} <music21.humdrum.spineParser.GlobalReference system-decoration '{(s1,s2)}'>
```

I don't know Humdrum, so I fear I can't be on the rescue mission here, but at a glance, programmatically setting `isFirstVoice=True` looks suspicious; I bet only two voices are supported currently.

https://github.com/cuthbertLab/music21/blob/60d91ddaf4a7398337181a6168c9ec45abcb93b3/music21/humdrum/spineParser.py#L617-L627

**Comment by jacobtylerwalls** [comment] 2021-03-04 17:11
Can you engineer an example with just 3 voices and no ties?

**Comment by napulen** [comment] 2021-03-04 19:00
Yeah, sure! I'll spend some more time crafting examples and seeing what I find.

Really appreciate the pointers here on the number of voices. That sounds quite plausible.

**Comment by jacobtylerwalls** [comment] 2021-03-04 19:33
While I'm here, I'm noticing Humdrum doesn't create `PartStaff` objects for the piano hands, nor a `StaffGroup` object to represent the brace (I suppose that's what the `GlobalReference` is for)? We need that for MusicXML to export correctly on versions >=6.5, otherwise you get the old behavior (in your screenshot) of ungrouped staffs.

**Comment by jacobtylerwalls** [comment] 2021-03-04 20:37
https://github.com/cuthbertLab/music21/blob/60d91ddaf4a7398337181a6168c9ec45abcb93b3/music21/humdrum/spineParser.py#L2914-L2922

**Comment by jacobtylerwalls** [comment] 2021-03-05 15:58
@napulen looks like a dupe of #62, which has a minimal example, so I would say don't expend more effort coming up with another one!

**Comment by mscuthbert** [comment] 2021-03-05 20:01
Yes -- none of David Huron's original examples merged more than one staff at once, but his spec doesn't forbid it so it's something I'd like to include.

However, without versioned revisions to the humdrum standard, I'm only committing to supporting the original standard.  Post musicxml/MEI/etc. I'm a bit baffled that people are still writing new Kern-only humdrum files.

**Comment by napulen** [comment] 2021-03-08 18:53
@jacobtylerwalls thanks for finding the reference to https://github.com/cuthbertLab/music21/issues/62. I think the discussion there makes it very clear what the problem is. 

I will try to come up with a PR for this. Maybe we can close two issues at once :).

@mscuthbert I understand your point about versioned revisions. Honestly, I have parsed many examples of Humdrum files for the past months/years and generally it's robust (talking about notes and duration information only), so I think the current support is good enough already. I am personally interested in this voice behaviour being improved, so I'll try to push the PR for this one.

Regarding reasons why people still write humdrum, I don't know about others, I have a few reasons why I like humdrum:

- Just last week, I had a Compressed MusicXML file with two voices that once parsed-and-exported by music21, it distributed the layers across four voices instead of two. I am sure this was due to some defect on the MusicXML file (and not music21), but it was a silent error; no warnings/complains anywhere, so I couldn't figure out why. I moved to Humdrum and I found an issue in one of the durations. And it seems that correcting that duration fixed it. Took me a fraction of the time it would take me to debug the content of a MusicXML file. If I were to draw a comparison to text, Humdrum feels like Markdown while MusicXML feels like RTF. I prefer to look for encoding mistakes in a Markdown file.
- I tend to write unit tests in Humdrum and put them as text strings in python. It's quite less verbose than other formats for polyphonic representations. Probably the most widespread use of Humdrum I do nowadays. My test code is full of humdrum strings like the one I put on the *steps to reproduce* section of this issue.
- Lots of existing data already.
- There's a community. You feel less alone when working with that data.

I appreciate the support and commitment of music21 to at least the original Humdrum standard. Thanks for that.

Cheers.

**Comment by jacobtylerwalls** [comment] 2021-06-30 14:36
Hi Néstor, hope you're well. Is it alright to close this as a duplicate of #62? They're already linked, so it should be a simple matter to navigate back to the discussion and test case here.

**Closed by jacobtylerwalls** 2021-06-30 14:36 UTC

**Comment by napulen** [comment] 2021-06-30 14:44
Hi Jacob, sorry for the long silence! I am fine, just swamped in responsibilities beyond what I expected for this time of the year.

Yes, that is fine. And sorry that I didn't bring a PR for this, I was planning to do so but things got on the way.

I hope you are doing well.
