### ISSUE TITLE
MEI transposition is still broken

### ISSUE THREAD

**Issue by crantila** [cuthbertLab/music21#140] opened 2016-01-28 21:44 UTC
As reported by @sonovice in issue #125 .

-----------------------------

Hmm, I still get an error on some files:

```
Traceback (most recent call last):
  File "C:/Users/Simon/Dropbox/Dissertation/Code/tests/mei2wave.py", line 17, in <module>
    stream.toSoundingPitch(inPlace=True)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\stream\__init__.py", line 4062, in toSoundingPitch
    p.toSoundingPitch(inPlace=True)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\stream\__init__.py", line 4069, in toSoundingPitch
    returnObj._transposeByInstrument(reverse=False, inPlace=True)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\stream\__init__.py", line 4009, in _transposeByInstrument
    inPlace=True)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\stream\__init__.py", line 5985, in extendDurationAndGetBoundaries
    raise StreamException('no elements of this class defined in this Stream')
music21.exceptions21.StreamException: no elements of this class defined in this Stream
```

Code:

```
stream = converter.parseFile('A_mov6_6.mei', None, "mei", True)
stream.toSoundingPitch(inPlace=True)
```

File: https://www.dropbox.com/s/rdvwjg3hv7kcj5p/A_mov6_6.mei?dl=

**Comment by mscuthbert** [comment] 2016-01-29 15:10
Commit  9a9318a fixes the problem of the exception being raised for calling .toSoundingPitch() on a Stream without Instruments.  If the mei file does have instruments, though, then issue is not fixed.

**Comment by sonovice** [comment] 2016-02-16 08:03
Active polling ;-)

**Comment by mscuthbert** [comment] 2016-02-16 19:17
pinged, but I don't have a solution, since I don't know MEI. :-)

**Comment by ahankinson** [comment] 2016-02-16 22:30
Although this may not be the problem, it doesn't hurt: You MEI is not valid with the latest version of MEI:

```
$> xmllint --noout --relaxng ~/Documents/code/git/music-encoding/build/mei-all.rng ~/Downloads/A_mov6_6.mei
/Users/ahankins/Downloads/A_mov6_6.mei:16: element music: Relax-NG validity error : Invalid attribute meiversion for element music
/Users/ahankins/Downloads/A_mov6_6.mei:7: element mei: Relax-NG validity error : Invalid attribute meiversion for element mei
/Users/ahankins/Downloads/A_mov6_6.mei fails to validate

**Comment by ahankinson** [comment] 2016-02-16 22:32
If you take the `meiversion` attributes off of `<music>` it will validate -- but that probably doesn't help you. :)

**Comment by crantila** [comment] 2016-02-25 21:20
I'm sorry I haven't been able to look at these issues yet. They are on my "TODO" list, but unfortunately not at the top for a while.

**Comment by sonovice** [comment] 2016-05-18 11:06
Okay, I tried to look a bit into it:
```
from music21 import *
stream = converter.parseFile('A_mov6.mei', None, "mei", True)

for i in stream.recurse().getInstruments():
    print(i, i.transposition)

stream.toSoundingPitch(inPlace=True)

for i in stream.recurse().getInstruments():
    print(i, i.transposition)
```
outputs this for the given file:
```
2: Clarinetti in A.: Alto <music21.interval.Interval m-3>
3: Corni in A.: Alto <music21.interval.Interval m-3>
7: Viole: Viola None
2: Clarinetti in A.: Alto <music21.interval.Interval m-3>
3: Corni in A.: Alto <music21.interval.Interval m-3>
7: Viole: Viola None
```
(The incorrectly recognized instrument names are another issue, see #163)

It seems as if the transposition information are correctly parsed, but on a wrong level in the stream. Without using `recursive()`, the output would be empty.

Is `toSoundingPitch()` supposed to make a deep search in the hierarchy?

**Comment by crantila** [comment] 2016-05-18 13:52
Thanks for looking into this, @sonovice! I don't know about `toSoundingPitch()`, but from your description this is a recurring problem I've faced with the MEI-to-music21 converter: the tension between what is possible in music21 and what is expected. This isn't a failing of MEI or music21, but simply what happens when you convert between representations.

We'll have to see which solution @mscuthbert prefers, but I'm open to changing the MEI converter if requested.

**Comment by mscuthbert** [comment] 2016-05-19 17:58
Be sure to check what the actual pitches are after calling `toSoundingPitch()`.  The instrument.transposition object does not change after `toSoundingPitch()` or not -- what changes are the notes and the .atSoundingPitch attribute.  If there's still a bug after checking that, let me know.

I don't know at what level MEI places instruments in a Stream.  If they're placed at the same level as MusicXML (or MIDI, etc.) does then there shouldn't be any difference in behavior between the different input formats.  If it's at a different level then it's a different issue -- either MEI should change (bug), the other formats should change (bug), or the search mechanism should be extended to find instruments at different levels (enhancement).  Thanks!  Best, Myke

**Comment by mscuthbert** [comment] 2016-05-19 17:59
(that sounded a bit curt -- i meant, THANKS to all who are reporting, investigating, and fixing bugs!)

**Comment by sonovice** [comment] 2016-05-19 19:11
I looked at the actual music21 stream, [here is a diff](https://www.diffchecker.com/3fuuosnw).
It looks correctly, but the MIDI output sounds very weird as in wrong notes. Afterall it does not look like an actual MEI bug, sorry for the trouble. I will investage further...

**Comment by mscuthbert** [comment] 2016-05-19 19:19
It looks like no bug here.  If MIDI is ignoring the "atSoundingPitch()" etc. then that's a different bug. :-)

**Comment by sonovice** [comment] 2016-05-19 19:49
Okay, I just pulled the latest version from git, and NOW it sounds really weird. MIDI output get's it totally wrong, no transposition whatsoever. At least now I can be sure that the MIDI output was infact correctly transposing, even without a call to `atSoundingPitch()`. Looks like something has destroyed the instrument parsing. Shall I open a new issue?

**Comment by mscuthbert** [comment] 2016-05-19 19:57
I'm going to need more specific and simple tests (generally, one or two notes and one or two instruments is much better). I can only fix one bug at a time.  If this is not a bug in MEI then we should close this and move the bug to where it actually is -- but is it a MIDI bug or instrument bug?

**Comment by mscuthbert** [comment] 2016-06-13 18:23
Is the original issue fixed now and can this bug be closed? Thanks!

**Comment by crantila** [comment] 2016-06-15 20:12
I believe this situation is still unresolved:

> I don't know at what level MEI places instruments in a Stream. If they're placed at the same level as MusicXML (or MIDI, etc.) does then there shouldn't be any difference in behavior between the different input formats. If it's at a different level then it's a different issue -- either MEI should change (bug), the other formats should change (bug), or the search mechanism should be extended to find instruments at different levels (enhancement).

The MEI-to-music21 converter does not put instruments in the same place as the MusicXML converter. I suggest the best resolution is to *both* enhance the search mechanism so it finds instruments at different levels (thereby removing a potentially unexpected limitation) *and* to change where the MEI converter puts instruments (thereby making the converters as similar as possible).

Does that seem right?

**Comment by mscuthbert** [comment] 2016-06-16 02:44
That's a good solution. 

There way be other changes to the find instruments routines but I'll make them transparent to users doing .show(), .write() etc.

**Comment by mscuthbert** [comment] 2016-08-22 19:48
Let's separate this into different bugs, since some are solved and some not.

**Closed by mscuthbert** 2016-08-22 19:48 UTC
Labels: activity:current, verified:no
