### ISSUE TITLE
StreamException: the object * is already found in this stream

### ISSUE THREAD

**Issue by euneirophrenia** [cuthbertLab/music21#223] opened 2017-06-03 10:24 UTC
Hi! Nice library to begin with and sorry if I'm posting an issue if the issue turns out to actually be my brain.

I'm trying to extract some features from a midi file.

Feature: jSymbolic.AcousticGuitarFractionFeature
File      : http://midkar.com/jazz/500_miles_high-Chick-Corea_ee.mid
Code: 
```python
import music21.features as feat
s=music21.converter.parse("./Test/500_miles_high-Chick-Corea_ee.mid")
ext=feat.jSymbolic.AcousticGuitarFractionFeature
print (ext(s).extract().vector)
```

Problem: 
```python
Traceback (most recent call last):
File "main.py", line 16, in <module>
    print(ext(s).extract().vector)
File "C:\Python34\lib\site-packages\music21\features\base.py", line 209, in extract
    self._process() # will set Feature object to _feature
File "C:\Python34\lib\site-packages\music21\features\jSymbolic.py", line 3462, in _process
    s = self.data['partitionByInstrument']`
File "C:\Python34\lib\site-packages\music21\features\base.py", line 627, in __getitem__
    return self._forms[key]
File "C:\Python34\lib\site-packages\music21\features\base.py", line 341, in __getitem__
    x = instrument.partitionByInstrument(self._base)
File "C:\Python34\lib\site-packages\music21\instrument.py", line 1730, in partitionByInstrument
    p.insert(sub.elementOffset(e), e)
File "C:\Python34\lib\site-packages\music21\stream\__init__.py", line 1677, in insert
    self._addElementPreProcess(element)
File "C:\Python34\lib\site-packages\music21\stream\core.py", line 290, in _addElementPreProcess
    (element, id(element), self, id(self)))
music21.exceptions21.StreamException: the object (<music21.tempo.MetronomeMark larghetto Quarter=60.0>, id()=116292632) is already found in this Stream (<music21.stream.Part Flute>, id()=306686944)
```

(i'm so sorry for the poor formatting, hope it's still somewhat readable EDIT: fixed it a little).
I've been going through the same problems as in this issue 
https://github.com/cuthbertLab/music21/issues/150
(even the opening one, by the way, I had to change 2 lines at jsymbolic.py 3130 and 3216, adding a `and i.midiprogram is not None` ).
The error is essentially the same as in the last comment. I've searched every single issue here but never found the right one, so I am posting. 

I strongly suspect it's a file-related issue, i.e. a problem with the specific file. 
Indeed, other files run normally with the same code, so the question is:
is it the file to be bad formatted (and so should i scrap it) or is it the code to miss something, such as a control or something?

Thank you so much for the good work, I really appreciate it!

**Comment by mscuthbert** [comment] 2017-06-05 17:02
I believe that the problem is in partitionByInstrument, so instrument.partitionByInstrument(s) also gives the bug.  (It'd really help if the piece were shorter -- the length makes debugging very hard).

**Comment by mscuthbert** [comment] 2017-06-05 17:35
Fixed in newest commit.  Thanks!

**Closed** 2017-06-05 17:35 UTC

**Comment by euneirophrenia** [comment] 2017-06-05 18:20
Thank you sooo much! Keep up the good work!
