### ISSUE TITLE
Multiple Voices causes problems in export to musicxml

### ISSUE THREAD

**Issue by pconerly** [cuthbertLab/music21#368] opened 2019-02-04 23:34 UTC
Generic title because there's a handful of issues:

When there are multiple voices, there are things missing in the exported score.
- KeySignature (see #367 )
- Tempo
- Automatic transposition of notes into the key.

The best way to see this is the before/after of my two images. You can see  (I changed my local library to include the #367 fix, so it has KeySignature.)

The only difference is the addition of 1 note at the beginning.

**One Voice:**
<img width="923" alt="screen shot 2019-02-04 at 3 26 38 pm" src="https://user-images.githubusercontent.com/469808/52244383-391c4100-2892-11e9-93b7-880e9a537e51.png">

**Two Voice:**
<img width="920" alt="screen shot 2019-02-04 at 3 26 23 pm" src="https://user-images.githubusercontent.com/469808/52244389-3c173180-2892-11e9-9326-65d8c2caa686.png">

**Comment by mscuthbert** [comment] 2019-11-14 14:09
Sorry I missed this issue so never commented on it.  Can you send along a minimum file that causes this bug?  Is the bug because the measures do not fill up?  It'd be most helpful to know what your input is and what you expect the output to be.

**Comment by jacobtylerwalls** [comment] 2020-07-15 13:14
Hi @pconerly in writing up something from the mailing list in #577 I think I covered your case with the accidentals showing up here -- but could you retest tempo? If tempo is still an issue, let's update this ticket title to just track that and please include a code example that consisting of just a few lines of `stream.append` commands that reproduces. Thanks.

**Comment by mscuthbert** [comment] 2020-07-18 03:21
There have been two major patches connected to similar issues, and no test case, so closing for now.  feel free to reopen if bug continues.

**Closed by mscuthbert** 2020-07-18 03:21 UTC
