### ISSUE TITLE
Chordify missed some slices when exporting to MIDI

### ISSUE THREAD

**Issue by juyaolongpaul** [cuthbertLab/music21#502] opened 2019-12-19 04:48 UTC
This is the source file I had: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <work>
    <work-title>Herr Christ, der ein'ge Gotts Sohn</work-title>
    </work>
  <movement-title>Herr Christ, der ein'ge Gotts Sohn</movement-title>
  <identification>
    <creator type="composer">Bach, Johann Sebastian</creator>
    <encoding>
      <software>MuseScore 3.3.2</software>
      <encoding-date>2019-12-18</encoding-date>
      <supports element="accidental" type="yes"/>
      <supports element="beam" type="yes"/>
      <supports element="print" attribute="new-page" type="yes" value="yes"/>
      <supports element="print" attribute="new-system" type="yes" value="yes"/>
      <supports element="stem" type="yes"/>
      </encoding>
    </identification>
  <defaults>
    <scaling>
      <millimeters>7</millimeters>
      <tenths>40</tenths>
      </scaling>
    <page-layout>
      <page-height>1697.14</page-height>
      <page-width>1200</page-width>
      <page-margins type="even">
        <left-margin>57.1429</left-margin>
        <right-margin>57.1429</right-margin>
        <top-margin>57.1429</top-margin>
        <bottom-margin>114.286</bottom-margin>
        </page-margins>
      <page-margins type="odd">
        <left-margin>57.1429</left-margin>
        <right-margin>57.1429</right-margin>
        <top-margin>57.1429</top-margin>
        <bottom-margin>114.286</bottom-margin>
        </page-margins>
      </page-layout>
    <word-font font-family="FreeSerif" font-size="10"/>
    <lyric-font font-family="FreeSerif" font-size="11"/>
    </defaults>
  <credit page="1">
    <credit-words default-x="1142.86" default-y="1498.31" justify="right" valign="bottom" font-size="12">Bach, Johann Sebastian</credit-words>
    </credit>
  <credit page="1">
    <credit-words default-x="600" default-y="1640" justify="center" valign="top" font-size="24">Ertöt uns durch dein Güte </credit-words>
    </credit>
  <part-list>
    <score-part id="P1">
      <part-name>Voice</part-name>
      <part-abbreviation>V</part-abbreviation>
      <score-instrument id="P1-I1">
        <instrument-name>Voice</instrument-name>
        </score-instrument>
      <midi-device id="P1-I1" port="1"></midi-device>
      <midi-instrument id="P1-I1">
        <midi-channel>1</midi-channel>
        <midi-program>53</midi-program>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    <score-part id="P2">
      <part-name>Voice</part-name>
      <part-abbreviation>V</part-abbreviation>
      <score-instrument id="P2-I1">
        <instrument-name>Voice</instrument-name>
        </score-instrument>
      <midi-device id="P2-I1" port="1"></midi-device>
      <midi-instrument id="P2-I1">
        <midi-channel>3</midi-channel>
        <midi-program>53</midi-program>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    <score-part id="P3">
      <part-name>Voice</part-name>
      <part-abbreviation>V</part-abbreviation>
      <score-instrument id="P3-I1">
        <instrument-name>Voice</instrument-name>
        </score-instrument>
      <midi-device id="P3-I1" port="1"></midi-device>
      <midi-instrument id="P3-I1">
        <midi-channel>5</midi-channel>
        <midi-program>53</midi-program>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    <score-part id="P4">
      <part-name>Voice</part-name>
      <part-abbreviation>V</part-abbreviation>
      <score-instrument id="P4-I1">
        <instrument-name>Voice</instrument-name>
        </score-instrument>
      <midi-device id="P4-I1" port="1"></midi-device>
      <midi-instrument id="P4-I1">
        <midi-channel>7</midi-channel>
        <midi-program>53</midi-program>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    </part-list>
  <part id="P1">
    <measure number="0" implicit="yes" width="214.25">
      <print>
        <system-layout>
          <system-margins>
            <left-margin>66.85</left-margin>
            <right-margin>0.00</right-margin>
            </system-margins>
          <top-system-distance>211.69</top-system-distance>
          </system-layout>
        </print>
      <attributes>
        <divisions>2</divisions>
        <key>
          <fifths>-1</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
          </clef>
        </attributes>
      <note default-x="105.37" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="1" width="497.66">
      <note default-x="10.00" default-y="-20.00">
        <pitch>
          <step>B</step>
          <alter>-1</alter>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>down</stem>
        </note>
      <note default-x="137.91" default-y="-30.00">
        <pitch>
          <step>G</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="240.24" default-y="-25.00">
        <pitch>
          <step>A</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="368.15" default-y="-30.00">
        <pitch>
          <step>G</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="2" width="306.95">
      <note default-x="13.80" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>6</duration>
        <voice>1</voice>
        <type>half</type>
        <dot/>
        <stem>up</stem>
        <notations>
          <fermata type="upright"/>
          </notations>
        </note>
      <barline location="right">
        <bar-style>light-light</bar-style>
        </barline>
      </measure>
    </part>
  <part id="P2">
    <measure number="0" implicit="yes" width="214.25">
      <print>
        <staff-layout number="1">
          <staff-distance>65.00</staff-distance>
          </staff-layout>
        </print>
      <attributes>
        <divisions>2</divisions>
        <key>
          <fifths>-1</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
          </clef>
        </attributes>
      <note default-x="105.37" default-y="-155.00">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="1" width="497.66">
      <note default-x="10.00" default-y="-135.00">
        <pitch>
          <step>G</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>up</stem>
        <beam number="1">begin</beam>
        </note>
      <note default-x="73.96" default-y="-140.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <accidental>natural</accidental>
        <stem>up</stem>
        <beam number="1">end</beam>
        </note>
      <note default-x="137.91" default-y="-145.00">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="240.24" default-y="-140.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="368.15" default-y="-145.00">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="2" width="306.95">
      <note default-x="13.80" default-y="-155.00">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>6</duration>
        <voice>1</voice>
        <type>half</type>
        <dot/>
        <stem>up</stem>
        <notations>
          <fermata type="upright"/>
          </notations>
        </note>
      <barline location="right">
        <bar-style>light-light</bar-style>
        </barline>
      </measure>
    </part>
  <part id="P3">
    <measure number="0" implicit="yes" width="214.25">
      <print>
        <staff-layout number="1">
          <staff-distance>65.00</staff-distance>
          </staff-layout>
        </print>
      <attributes>
        <divisions>2</divisions>
        <key>
          <fifths>-1</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
          <clef-octave-change>-1</clef-octave-change>
          </clef>
        </attributes>
      <note default-x="105.37" default-y="-235.00">
        <pitch>
          <step>A</step>
          <octave>3</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="1" width="497.66">
      <note default-x="10.00" default-y="-220.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>down</stem>
        </note>
      <note default-x="137.91" default-y="-225.00">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>down</stem>
        </note>
      <note default-x="240.24" default-y="-225.00">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>down</stem>
        </note>
      <note default-x="368.15" default-y="-225.00">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>down</stem>
        <beam number="1">begin</beam>
        </note>
      <note default-x="432.11" default-y="-230.00">
        <pitch>
          <step>B</step>
          <alter>-1</alter>
          <octave>3</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>down</stem>
        <beam number="1">end</beam>
        </note>
      </measure>
    <measure number="2" width="306.95">
      <note default-x="13.80" default-y="-235.00">
        <pitch>
          <step>A</step>
          <octave>3</octave>
          </pitch>
        <duration>6</duration>
        <voice>1</voice>
        <type>half</type>
        <dot/>
        <stem>up</stem>
        <notations>
          <fermata type="upright"/>
          </notations>
        </note>
      <barline location="right">
        <bar-style>light-light</bar-style>
        </barline>
      </measure>
    </part>
  <part id="P4">
    <measure number="0" implicit="yes" width="214.25">
      <print>
        <staff-layout number="1">
          <staff-distance>65.00</staff-distance>
          </staff-layout>
        </print>
      <attributes>
        <divisions>2</divisions>
        <key>
          <fifths>-1</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <clef>
          <sign>F</sign>
          <line>4</line>
          </clef>
        </attributes>
      <note default-x="105.37" default-y="-325.00">
        <pitch>
          <step>F</step>
          <octave>3</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>down</stem>
        </note>
      </measure>
    <measure number="1" width="497.66">
      <note default-x="10.00" default-y="-355.00">
        <pitch>
          <step>G</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>up</stem>
        <beam number="1">begin</beam>
        </note>
      <note default-x="73.96" default-y="-350.00">
        <pitch>
          <step>A</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>up</stem>
        <beam number="1">end</beam>
        </note>
      <note default-x="137.91" default-y="-345.00">
        <pitch>
          <step>B</step>
          <alter>-1</alter>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="240.24" default-y="-350.00">
        <pitch>
          <step>A</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>up</stem>
        <beam number="1">begin</beam>
        </note>
      <note default-x="304.20" default-y="-345.00">
        <pitch>
          <step>B</step>
          <alter>-1</alter>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>up</stem>
        <beam number="1">end</beam>
        </note>
      <note default-x="368.15" default-y="-340.00">
        <pitch>
          <step>C</step>
          <octave>3</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="2" width="306.95">
      <note default-x="13.80" default-y="-360.00">
        <pitch>
          <step>F</step>
          <octave>2</octave>
          </pitch>
        <duration>6</duration>
        <voice>1</voice>
        <type>half</type>
        <dot/>
        <stem>up</stem>
        <notations>
          <fermata type="upright"/>
          </notations>
        </note>
      <barline location="right">
        <bar-style>light-light</bar-style>
        </barline>
      </measure>
    </part>
  </score-partwise>
```

I added Chodify voice using this code (I used music21 v.5.1.0):
`s_MIDI = converter.parse(FILE_PATH)`
`s_MIDI_Chords = s_MIDI.chordify()`
`s_MIDI.insert(0, s_MIDI_Chords)`
Then I exported it to MIDI and musicXML using `s_MIDI.write(FILE_FORMAT, FILE_PATH)` function. For musicXML, it works fine since all the chordify slices are included, but for MIDI, some of them are lost.

Here are the screenshots when I opened them using MuseScore (v.3.3.2):

MusicXML: 

![image](https://user-images.githubusercontent.com/9313094/71145447-afe2d400-21ef-11ea-8938-51dbdf11dff6.png)

MIDI:

![image](https://user-images.githubusercontent.com/9313094/71145478-cf79fc80-21ef-11ea-8977-4199810ee2fa.png)

I need to use this function for my current research project, and it will be great if it can be fixed sometime. Thanks for the help! Please let me know if you have any questions!

Best,

Yaolong

**Comment by dhgutteridge** [comment] 2019-12-30 00:25
Just as an additional detail, I can duplicate this issue with music21 v. 5.7.2 as well.

**Comment by mscuthbert** [comment] 2019-12-30 15:57
hi -- sorry I missed this issue when it first was posted and just saw it now.  What does the music21 stream look like that you are chordifying and can you get to a minimum possible set that replicates the problem?  When debugging any additional piece of information not needed to solve the problem can double or triple the time to solve it and make it unlikely a fix will be in the next version.  Is the problem in the MIDI conversion or in the chordification?

**Comment by juyaolongpaul** [comment] 2019-12-30 19:39
Hi Michael,

Thank you for your help. I posted a minimum set (musicXML and the music21 commands I used for conversion) at the beginning of this thread. I think it should replicate the problem. 

From what I observed, the problem is not the chordification, but the MIDI conversion, since the chordify voice managed to export correctly in musicXML, not MIDI. Does it help?

Please let me know if you have any questions. Thanks!

**Comment by mscuthbert** [comment] 2019-12-30 21:46
Hi @juyaolongpaul -- a minimum set usually consists of just two to four notes -- or something like that.  Do all four parts need to be present in order to create the problem?  Does the Chords staff have to be reinserted into the Score in order to see the problem?  I'd really like a program of no more than 10-20 lines of code w/o converter/corpus .parse() calls that I can use to see the problem.  Otherwise it won't be something I can get to for months or years.

**Comment by juyaolongpaul** [comment] 2019-12-30 23:12
Hi @mscuthbert, I understand your concern. I did experiment with the problem a bit, and I could replicate the problem with just 5 notes in 2 voices. Here is the source XML file.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <identification>
    <encoding>
      <software>MuseScore 3.4.0</software>
      <encoding-date>2019-12-30</encoding-date>
      <supports element="accidental" type="yes"/>
      <supports element="beam" type="yes"/>
      <supports element="print" attribute="new-page" type="yes" value="yes"/>
      <supports element="print" attribute="new-system" type="yes" value="yes"/>
      <supports element="stem" type="yes"/>
      </encoding>
    </identification>
  <defaults>
    <scaling>
      <millimeters>7.05556</millimeters>
      <tenths>40</tenths>
      </scaling>
    <page-layout>
      <page-height>1584</page-height>
      <page-width>1224</page-width>
      <page-margins type="even">
        <left-margin>56.6929</left-margin>
        <right-margin>56.6929</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      <page-margins type="odd">
        <left-margin>56.6929</left-margin>
        <right-margin>56.6929</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      </page-layout>
    <word-font font-family="FreeSerif" font-size="10"/>
    <lyric-font font-family="FreeSerif" font-size="11"/>
    </defaults>
  <part-list>
    <score-part id="P1">
      <part-name>Piano</part-name>
      <part-abbreviation>Pno.</part-abbreviation>
      <score-instrument id="P1-I1">
        <instrument-name>Piano</instrument-name>
        </score-instrument>
      <midi-device id="P1-I1" port="1"></midi-device>
      <midi-instrument id="P1-I1">
        <midi-channel>1</midi-channel>
        <midi-program>1</midi-program>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    </part-list>
  <part id="P1">
    <measure number="1" width="391.64">
      <print>
        <system-layout>
          <system-margins>
            <left-margin>21.00</left-margin>
            <right-margin>697.97</right-margin>
            </system-margins>
          <top-system-distance>70.00</top-system-distance>
          </system-layout>
        <staff-layout number="2">
          <staff-distance>65.00</staff-distance>
          </staff-layout>
        </print>
      <attributes>
        <divisions>2</divisions>
        <key>
          <fifths>0</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <staves>2</staves>
        <clef number="1">
          <sign>G</sign>
          <line>2</line>
          </clef>
        <clef number="2">
          <sign>F</sign>
          <line>4</line>
          </clef>
        </attributes>
      <note default-x="82.47" default-y="-15.00">
        <pitch>
          <step>C</step>
          <octave>5</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>down</stem>
        <staff>1</staff>
        <beam number="1">begin</beam>
        </note>
      <note default-x="148.07" default-y="-20.00">
        <pitch>
          <step>B</step>
          <alter>-1</alter>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <accidental>flat</accidental>
        <stem>down</stem>
        <staff>1</staff>
        <beam number="1">end</beam>
        </note>
      <note default-x="213.32" default-y="-25.00">
        <pitch>
          <step>A</step>
          <octave>4</octave>
          </pitch>
        <duration>6</duration>
        <voice>1</voice>
        <type>half</type>
        <dot/>
        <stem>up</stem>
        <staff>1</staff>
        </note>
      <backup>
        <duration>8</duration>
        </backup>
      <note default-x="82.47" default-y="-130.00">
        <pitch>
          <step>C</step>
          <octave>3</octave>
          </pitch>
        <duration>2</duration>
        <voice>5</voice>
        <type>quarter</type>
        <stem>up</stem>
        <staff>2</staff>
        </note>
      <note default-x="213.32" default-y="-150.00">
        <pitch>
          <step>F</step>
          <octave>2</octave>
          </pitch>
        <duration>6</duration>
        <voice>5</voice>
        <type>half</type>
        <dot/>
        <stem>up</stem>
        <staff>2</staff>
        </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        </barline>
      </measure>
    </part>
  </score-partwise>

```
I used music21 to add the chordify part:
`s_MIDI = converter.parse(FILE_PATH)`
`s_MIDI_Chords = s_MIDI.chordify()`
`s_MIDI.insert(0, s_MIDI_Chords)`
Then I exported it to MIDI using `s_MIDI.write('mid', FILE_PATH)` function. As you can see in the screenshot below (opened using MuseScore v.3.3.2), there are only 2 chordify slices (highlighted in blue, should have been 3). When I exported the same Score object to musicXML, there was no issue like this. 

![image](https://user-images.githubusercontent.com/9313094/71604419-d2e67f80-2b2f-11ea-83d7-abb371d6987a.png)

Thanks for the help.

**Comment by jacobtylerwalls** [comment] 2020-06-23 03:47
Same issue as #430, but nice work on a smaller reproducing example. You actually just need the first beat, and you can build the chord directly instead of using `chordify()`:

```
s = stream.Stream()
n1 = note.Note('C5')
n1.quarterLength = 0.5
n2 = note.Note('Bb4')
n2.quarterLength = 0.5
n3 = note.Note('C3')
n3.quarterLength = 0.5
n3.tie = tie.Tie('start')
n4 = note.Note('C3')
n4.quarterLength = 0.5
n4.tie = tie.Tie('stop')

c1 = chord.Chord([n1, n3])
c2 = chord.Chord([n2, n4])
s.append([c1, c2])

stripped = s.stripTies()
stripped.show('t')
>>>  {0.0} <music21.chord.Chord C5 C3>
```
You are experiencing this during MIDI conversion because MIDI conversion always calls `stripTies()`. The issue is that `stripTies()` becomes slightly brittle when chords are involved; in your case, chords 1 and 2 are tied, but not all of the chord members are. Still, `stripTies()` prolongs the first verticality and removes the second one.

You can fork the repo in order to stop stripping ties during MIDI conversion if that helps move your project forward, but in terms of a fix, I figure it would be wise for `stripTies()` to bail out when it encounters `Chord` objects where not every member is tied. Better not to strip a few ties than to delete distinct verticalities, no?

**Closed** 2020-08-25 06:01 UTC
