### ISSUE TITLE
Diminuendo doesn't span all elements that are part of it

### ISSUE THREAD

**Issue by swesterfeld** [cuthbertLab/music21#1680] opened 2024-01-03 20:03 UTC
**music21 version**

`9.1.0`   

**Problem summary**

After reading an xml file, the spanned elements of the diminuendo in the xml doesn't correnspond to the spanned elements reported by music21.

**Steps to reproduce**

```
#!/usr/bin/env python3
from music21 import converter, note, stream, tempo, articulations, dynamics

score = converter.parse ("test.xml", format='musicxml')

DD = None
for part in score.parts:
  for element in part.flatten():
    if isinstance (element, dynamics.Diminuendo):
      DD = element
    if DD:
      print (element, element in DD.getSpannedElements())
```

XML input:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <work>
    <work-title>Unbenanntes Projekt 1</work-title>
  </work>
  <movement-title>Partie 1</movement-title>
  <identification>
    <encoding>
      <software>Dorico 4.3.30.1132</software>
      <encoding-date>2024-01-03</encoding-date>
    </encoding>
  </identification>
  <part-list>
    <score-part id="P1">
      <part-name>de6</part-name>
    </score-part>
  </part-list>
  <part id="P1">
    <measure number="1">
      <attributes>
        <divisions>4</divisions>
        <key number="1">
          <fifths>0</fifths>
          <mode>major</mode>
        </key>
        <time>
          <beats>6</beats>
          <beat-type>8</beat-type>
        </time>
        <staves>1</staves>
        <clef number="1">
          <sign>F</sign>
          <line>4</line>
        </clef>
      </attributes>
      <sound tempo="99"/>
      <direction placement="above" directive="yes">
        <direction-type>
          <words font-style="normal" font-weight="bold"> = 66</words>
        </direction-type>
        <direction-type>
          <metronome>
            <beat-unit>quarter</beat-unit>
            <beat-unit-dot/>
            <per-minute>66</per-minute>
          </metronome>
        </direction-type>
        <staff>1</staff>
      </direction>
      <note>
        <rest/>
        <duration>12</duration>
        <voice>1</voice>
        <type>whole</type>
        <staff>1</staff>
      </note>
    </measure>
    <measure number="2">
      <attributes>
        <divisions>4</divisions>
      </attributes>
      <direction placement="above">
        <direction-type>
          <dynamics>
            <ff/>
          </dynamics>
        </direction-type>
        <staff>1</staff>
      </direction>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <beam number="1">begin</beam>
        <beam number="2">begin</beam>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
      <direction>
        <direction-type>
          <wedge type="diminuendo" number="1"/>
        </direction-type>
        <staff>1</staff>
      </direction>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <beam number="1">continue</beam>
        <beam number="2">continue</beam>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <beam number="1">continue</beam>
        <beam number="2">continue</beam>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <beam number="1">continue</beam>
        <beam number="2">continue</beam>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <beam number="1">continue</beam>
        <beam number="2">continue</beam>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <beam number="1">end</beam>
        <beam number="2">end</beam>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <beam number="1">begin</beam>
        <beam number="2">begin</beam>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <beam number="1">continue</beam>
        <beam number="2">continue</beam>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <beam number="1">continue</beam>
        <beam number="2">continue</beam>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <beam number="1">continue</beam>
        <beam number="2">continue</beam>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <beam number="1">continue</beam>
        <beam number="2">continue</beam>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <beam number="1">end</beam>
        <beam number="2">end</beam>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
    </measure>
    <measure number="3">
      <attributes>
        <divisions>4</divisions>
      </attributes>
      <direction>
        <direction-type>
          <wedge type="stop" number="1"/>
        </direction-type>
        <staff>1</staff>
      </direction>
      <direction placement="above">
        <direction-type>
          <dynamics>
            <pp/>
          </dynamics>
        </direction-type>
        <staff>1</staff>
      </direction>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
        </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <staff>1</staff>
        <lyric number="1" placement="below">
          <syllabic>single</syllabic>
          <text>$</text>
        </lyric>
      </note>
      <note>
        <rest/>
        <duration>1</duration>
        <voice>1</voice>
        <type>16th</type>
        <staff>1</staff>
      </note>
      <note>
        <rest/>
        <duration>2</duration>
        <voice>1</voice>
        <type>eighth</type>
        <staff>1</staff>
      </note>
      <note>
        <rest/>
        <duration>2</duration>
        <voice>1</voice>
        <type>eighth</type>
        <staff>1</staff>
      </note>
      <note>
        <rest/>
        <duration>6</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <staff>1</staff>
      </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
      </barline>
    </measure>
  </part>
 ```

**Expected vs. actual behavior**

Ideally the diminuendo should span all elements except for start and end, which is also what I get if I load the xml in musescore3. However `test.py` outputs:

```
<music21.dynamics.Diminuendo <music21.note.Note G>> False
<music21.dynamics.Dynamic ff> False
<music21.note.Note G> False
<music21.note.Note G> True
<music21.note.Note G> True
<music21.note.Note G> True
<music21.note.Note G> True
<music21.note.Note G> False                                                <--- should be True
<music21.note.Note G> False                                                <--- should be True
<music21.note.Note G> True
<music21.note.Note G> True
<music21.note.Note G> True
<music21.note.Note G> True
<music21.note.Note G> False                                                <--- should be True
<music21.dynamics.Dynamic pp> False
<music21.note.Note G> False
<music21.note.Rest 16th> False
<music21.note.Rest eighth> False
<music21.note.Rest eighth> False
<music21.note.Rest dotted-quarter> False
<music21.bar.Barline type=final> False
```

So the diminuendo here doesn't span some notes in the middle. It also doesn't span the penultimate note. I've annotated the  problems inside the output shown here.
 
**More information**

This is done under Linux. The same problem occurs on macOS with music21 8.3.0 installed.

**Comment by jacobtylerwalls** [comment] 2024-01-10 19:27
Thanks for the clear report. Will be marking as a duplicate of #249. A PR adding this functionality to musicxml import would be very welcome.

In the meantime, you should be able to `.fill()` the spanners.

**Closed by jacobtylerwalls** 2024-01-10 19:27 UTC

**Comment by swesterfeld** [comment] 2024-01-21 17:41
> In the meantime, you should be able to `.fill()` the spanners.

I haven't been able to accomplish anything with .fill(), however, getFirst() and getLast() do something useful. Also I've observed that the beaming of the notes seems to have an effect on the contents of the diminuendo Spanner.
