### ISSUE TITLE
Parsing Local Corpora

### ISSUE THREAD

**Issue by arnavlavan** [cuthbertLab/music21#111] opened 2015-10-11 19:13 UTC
Dave Hofmann 	
Sep 22
Hi all,

I am trying to add a custom local corpus and might have found two issues. I tried with various versions, the latest being 2.0.11.

The first one relates to persisting local corpora. This is how I registered my corpus:
from music21 import corpus

myCorpus = corpus.LocalCorpus("Dave")
myCorpus.addPath("~/Documents/Musik/Noten/MusicXML")
print(myCorpus.directoryPaths)
myCorpus.save()
print("Exists in settings:", myCorpus.existsInSettings)
print(corpus.LocalCorpus.listLocalCorporaNames())

the output is:

('/Users/dave/Documents/Musik/Noten/MusicXML',)
Exists in settings: True
[None, 'Dave']

so everything seems to be working perfectly. These lines are written to my .music21rc:

<localCorporaSettings>
  <localCorpusSettings name="Dave">
    <localCorpusPath>/Users/dave/Documents/Musik/Noten/MusicXML</localCorpusPath>
  </localCorpusSettings>
</localCorporaSettings>
<localCorpusSettings />

So the path is expanded and stored correctly. Now when I run another program requesting the stored corpus, it won't be found:

print(corpus.LocalCorpus.listLocalCorporaNames())
myCorpus = corpus.LocalCorpus("Dave")
print(myCorpus.existsInSettings)

outputs:

[None]
False

Am I instantiating the corpus wrong? However there seems to be a general loading issue here since it doesn't even show up in the list of local corpora names.

The second question relates to how all compositions of a specific composer can be retrieved from my local corpus. There is the nice method corpus.getComposer(), which redirects to the core corpus so I won't find anything in my local corpus. The method getComposer() is not implemented in the class LocalCorpus. It would be great to make getComposer() consider local corpora transparently, or at least support a LocalCorpus-specific getComposer method. I guess the "global" option is not straight-forward because of possible name clashes (same folder names in different corpora are possible). Currently I am filtering all paths returned by getPaths() manually. Is there an easier way to achieve this?

If you can confirm any issues here, I can open according bug reports/tasks at github.

Thanks for your support and great work.
Best,
Dave

____________________________________________________

Adam Yodfat
12:30 AM (21 hours ago)

Hi
I am having a similar problem (I think, I hope I'm doing things right).
Using Music21 2.1, Win10, Python 3.4:

I tried to set up a local corpus this way:

from music21 import corpus

myCorpus = corpus.LocalCorpus("adam")
myCorpus.addPath("/db")
print(myCorpus.directoryPaths)
myCorpus.save()
print("Exists in settings:", myCorpus.existsInSettings)
print(corpus.LocalCorpus.listLocalCorporaNames())

and this is the output I got:

('/db',)
Exists in settings: True
[None, 'adam']

converter.parse is working fine for me:

>>> amba = converter.parse('/db/amba.xml')
>>> len(amba)
19
>>> type(amba)
<class 'music21.stream.Score'>

but than when I try to parse the file from the local corpus I get an error:

>>> amba1 = corpus.parse('amba.xml')
Traceback (most recent call last):
  File "C:\Python34\music21\corpus\corpora.py", line 310, in parse
    forceSource,
  File "C:\Python34\music21\corpus\corpora.py", line 330, in parse
    'if you are searching for a file on disk, use "converter" instead of "corpus".')
music21.corpus.CorpusException: Could not find a work that met this criterion: amba.mxl;if you are searching for a file on disk, use "converter" instead of "corpus".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    amba1 = corpus.parse('amba.xml')
  File "C:\Python34\music21\corpus\__init__.py", line 556, in parse
    forceSource=forceSource,
  File "C:\Python34\music21\corpus\corpora.py", line 318, in parse
    '. If you are searching for a file on disk, use "converter" instead of "corpus".')
music21.corpus.CorpusException: Could not find an xml or mxl work that met this criterion: amba.xml. If you are searching for a file on disk, use "converter" instead of "corpus".

I hope I didn't miss out something really basic. Thanks
Adam

**Comment by davehofmann** [comment] 2015-10-23 10:30
This can be subdivided into the following tasks:
* fix local corpora persistence, apparently they are stored but can not be loaded again
* support corpus.getComposer() considering local corpora or support LocalCorpus-specific getComposer() method
* support corpus.parse() considering local corpora or support LocalCorpus-specific parse() method

For the global approach possible name clashes (i.e. same subfolder names in core corpus and local corpora) must be taken into account.

**Comment by mscuthbert** [comment] 2015-10-31 20:54
Can you test again against the latest Master pull?  I fixed a bug that might be a big part of this yesterday.

**Comment by arnavlavan** [comment] 2015-10-31 21:03
I apologize but what exactly is the latest master pull? Should I reinstall from somewhere?

**Comment by mscuthbert** [comment] 2015-10-31 21:05
It's the git repository here: https://github.com/cuthbertLab/music21.git   with branch "master" -- if you're new to git, don't worry about it -- we'll get someone on it, it just might be a bit slower.  Unfortunately, because it's local it's one of the hardest parts of the system to test.

**Comment by mscuthbert** [comment] 2015-10-31 21:06
@davehofmann -- those should all already be there, but it appears that the bug is preventing it.  We do name clash resolving all the time, even in a single corpus.  For instance, ``corpus.parse('bach')``.

**Comment by arnavlavan** [comment] 2015-10-31 21:11
Thanks :)

**Comment by arnavlavan** [comment] 2015-11-04 14:12
Hi
I uninstalled the previous Music21 version I had, then reinstalled the Master pull and it is still not working, or so it seems (though the errors are slightly different this time):

Python 3.4.0 (v3.4.0:04f714765c13, Mar 16 2014, 19:25:23) [MSC v.1600 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> from music21 import *
music21: Certain music21 functions might need these optional packages: matplotlib, numpy, scipy;
if you run into errors, install them by following the instructions at
http://mit.edu/music21/doc/installing/installAdditional.html
>>> myCorpus = corpus.LocalCorpus("adam")
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    myCorpus = corpus.LocalCorpus("adam")
AttributeError: 'module' object has no attribute 'LocalCorpus'

>>> corpus.addPath('/db/')
>>> corpus.parse('amba.xml')
Traceback (most recent call last):
  File "C:\Python34\music21\corpus\corpora.py", line 467, in parse
    format=format
  File "C:\Python34\music21\corpus\corpora.py", line 488, in parse
    'if you are searching for a file on disk, use "converter" instead of "corpus".')
music21.corpus.CorpusException: Could not find a work that met this criterion: amba.mxl;if you are searching for a file on disk, use "converter" instead of "corpus".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    corpus.parse('amba.xml')
  File "C:\Python34\music21\corpus\__init__.py", line 485, in parse
    format=format
  File "C:\Python34\music21\corpus\corpora.py", line 476, in parse
    'use "converter" instead of "corpus".')
music21.corpus.CorpusException: Could not find an xml or mxl work that met this criterion: amba.xml. If you are searching for a file on disk, use "converter" instead of "corpus".
>>> print(corpus.directoryPaths)
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    print(corpus.directoryPaths)
AttributeError: 'module' object has no attribute 'directoryPaths'

**Comment by mscuthbert** [comment] 2015-11-04 14:31
Aargh.  That's one place that doesn't get tested automatically that I didn't realize got broken by the latest Git changes.  If you're on the latest Git pull, can you look at http://web.mit.edu/music21/doc/usersGuide/usersGuide_23_advancedCorpus.html and http://web.mit.edu/music21/doc/usersGuide/usersGuide_11_corpusSearching.html -- it shows that we removed aliases from "corpus.LocalCorpus()" and require now "corpus.corpora.LocalCorpus()" instead.  Thanks!

**Comment by davehofmann** [comment] 2015-11-04 16:07
Hi all,
I just tested local corpora using the latest master pull (4th November, b6023045c294f82b3aea061495139960b0e8a367).

I can confirm that the first issue regarding local corpora persistence is fixed :)

However the other issues are not resolved, at least not when trying this:
```python
myCorpus = corpus.corpora.LocalCorpus("Dave")
print(myCorpus.existsInSettings) # True, it was persisted properly :)
print(myCorpus.getPaths()) # works, lots of paths here

# ok let's see if we can access all compositions by the beatles, located in my local corpus in a subfolder beatles/...
print(myCorpus.getComposer("beatles")) # AttributeError: 'LocalCorpus' object has no attribute 'getComposer'
print(corpus.getComposer("beatles")) # empty list
print(corpus.corpora.getComposer("beatles")) # AttributeError: 'module' object has no attribute 'getComposer'

# let's try to parse a file
corpus.parse("beatles/NorwegianWood.xml") # music21.corpus.CorpusException: Could not find a work that met this criterion: beatles/NorwegianWood.mxl;if you are searching for a file on disk, use "converter" instead of "corpus".
```
Looking at the code I see that `corpus.getComposer()` redirects to CoreCorpus only.
`corpus.parse()` redirects to `corpora.Corpus.parse()` which in turn redirects to `corpus.getWorkList()`, which uses the CoreCorpus only. These methods should also consider local corpora.

Best regards
Dave

**Comment by mscuthbert** [comment] 2015-11-27 19:47
this whole structure needs a refactor.  There isn't a single place where we keep track of all the corpora to make it easy to iterate through each of them looking for a file. That's a problem.  Will keep this on the v.3 todo.  I did fix the `print(myCorpus.getComposer("beatles"))` problem.  Though "getComposer" is a misleading name -- it assumes that all directory names are composer names.  So bigger changes will be needed.

**Comment by mscuthbert** [comment] 2015-11-28 18:33
I've done that major rewrite now and it's in the master branch.  Let me know if it doesn't do everything you'd like it to do now. :-)

**Comment by davehofmann** [comment] 2015-12-02 10:59
Hi Myke,
I just tested the latest master pull. Unfortunately the local corpus persistnce functionality seems to be broken again. My corpus is stored in `.music21rc` but is not loaded again.
Furthermore I could not find any method in `corpus.manager` which returns a list of all files in a local corpus subfolder of my choice. Could you give me a hint which methods should be used for that? 

Thanks and best regards
Dave

**Comment by mscuthbert** [comment] 2016-06-27 18:42
I am afraid that I still don't have a method that lists these files in corpus.manager.  I'll try to get on this, but it might be a long time still I'm afraid.

**Comment by arnavlavan** [comment] 2016-06-27 18:46
Thanks for the efforts
Adam

**Comment by mscuthbert** [comment] 2016-08-22 19:34
I'm going to close this and make a separate issue "method in corpus.manager which returns a list of all files in a local corpus subfolder of my choice."  Feel free to reopen if there are other issues.

**Closed by mscuthbert** 2016-08-22 19:34 UTC
Labels: bug, configuration, verified:no

**Comment by mscuthbert** [comment] 2017-10-10 14:38
btw -- if you haven't tried localCorpora in v.5 alpha, please do so.  Way improved!
