### ISSUE TITLE
RomanNumeral and romanNumeralFromChord alignment

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#437] opened 2019-09-05 15:06 UTC
roman.RomanNumeral and roman.romanNumeralFromChord differ in their default handling of 6th and 7th degrees in minor (so round trips are spirals but not circles ... so to speak).

Should roman.Minor67Default and correctRNAlterationForMinor merge?

For instance ... 

```
ps = ['D', 'G#', 'B']
chd = chord.Chord(ps)
rn = roman.romanNumeralFromChord(chd, 'a')
print(rn.figure)

```
... returns 'viio6#4', but making a Roman numeral from that figure ...

```
rn = roman.RomanNumeral('viio6#4', 'a')
print([x.name for x in rn.pitches])

```
... returns ['D#4', 'G##', 'B#']

This can be overridden with seventhMinor=roman.Minor67Default.FLAT, so ...

```
rn = roman.RomanNumeral('viio6#4', 'a', seventhMinor=roman.Minor67Default.FLAT)
print([x.name for x in rn.pitches])

```
... returns ['D4', 'G#', 'B']
... but the defaults should probably align, right?

**Comment by mscuthbert** [comment] 2019-09-06 00:07
Is the problem with the 2nd inversion?  What happens if G# is put in the bass?  Just trying to isolate where the code is wrong (because this is definitely wrong)

**Comment by MarkGotham** [comment] 2019-09-06 13:21
Thanks Myke. Surprisingly, there's a difference depending on the order of pitches as input, not even the inversion.

So the same chord, including octaves, first in the 'correct order':

```
ps = ['G#4', 'B4', 'D5']
chd = chord.Chord(ps)
rn = roman.romanNumeralFromChord(chd, 'a')
print(rn.figure)
>>> 'viio'
```

```
rn = roman.RomanNumeral('viio', 'a')
print([x.name for x in rn.pitches])
>>> ['G#', 'B', 'D']
```
But the same pitches (with octave) entered in the 'wrong' order ...

```
ps = ['D5', 'G#4', 'B4']
chd = chord.Chord(ps)
rn = roman.romanNumeralFromChord(chd, 'a')
print(rn.figure)
>>> 'viio#853'
```

```
rn = roman.RomanNumeral('viio#853', 'a')
print([x.name for x in rn.pitches])
>>> ['G#', 'B', 'D', 'G##']
```

**Comment by jacobtylerwalls** [comment] 2020-11-11 01:24
Everything is fine if the figure is spelled the way I would expect, with the '#' before '64':
```
>>> rn = roman.RomanNumeral('viio#64', 'a')
>>> rn.pitches
(<music21.pitch.Pitch D5>, <music21.pitch.Pitch G#5>, <music21.pitch.Pitch B5>)
```
Is that the unexpected behavior: the # coming after the 6?

**Comment by jacobtylerwalls** [comment] 2020-11-11 03:45
I had a look, starting with plain `viio64`.

A `self.frontAlterationAccidental` of `#` is correctly derived so that `vii` -> `#vii` under the hood. The resulting `self.frontAlterationTransposeInterval` of `A1` is applied to each pitch, giving the intermediate result `G#, B#, D#`.

https://github.com/cuthbertLab/music21/blob/84a4a0a0678cb86db02a3b2d70f9824da152f945/music21/roman.py#L2165-L2170

Finally, we are saved in most instances when `_matchAccidentalsToQuality()` takes the bass of G# and performs a correction to `G#, B, D` to yield a diminished triad.

Now, with `viio64`, rinse and repeat, but for the bass of D#, and perform a correction to yield a diminished triad `D#, G##, B#`. Facepalm.

My instinct is that only the root needs to have the `frontAlterationTransposeInterval` applied to it. Figuring out how to pass the knowledge of the root to `_updatePitches()`, which otherwise recalculates roots, is not self-evident. Maybe we need to store a `.frontAlterationFixedRoot` or use something similar in `self._overrides`?

**Comment by mscuthbert** [comment] 2020-11-11 23:25
This is definitely a mess -- presumably the right path should be something like:

1) Determine the (un-front-altered) root pitch for ^1-^7 -- so in C major, #1 is still giving C at this point.
2) Determine implied quality based on the case, +, o, /o, etc.  Do not do anything with it.
3) If in minor AND on ^6 or ^7, look at things like `seventhMinor=roman.Minor67Default.FLAT` to determine the correct root pitch.  Use the implied quality to help.  Do not set frontAlterationTransposeInterval!  Except in the case of `.COURTESY` where we want to remove it from the figure.
4) Now search for an apply frontAlterationTransposeInterval to the root pitch.
5) Then generate the other pitches on the basis of implied quality, figures, etc.

(One other little fix to make:  I believe that `.figure` should be the "correct" way of spelling the figure in music21 (assuming the same seventhMinor, etc. are passed in).  I think we store a `.figureOriginal` or something like that to store what the user passed in.  Right now, we allow "IV6/4" etc., but .figure should be "IV64" since the slash doesn't mean anything).

**Comment by MarkGotham** [comment] 2020-11-12 16:40
Thanks @mscuthbert and @jacobtylerwalls ! I'd love to get this sorted out. Is it practical to collaborate or are all PRs single-author with others pitching in comments and hints only? If single-author then who's the chosen one?

**Comment by MarkGotham** [comment] 2020-11-12 16:41
For now, here's a draft re-write of the docs:

`Takes a chord object (chordObj) and returns a Roman numeral.
As Roman numerals are key-relative, this function makes most sense when the
user explicitly provides a key context with the keyObj variable.

>>> roman.romanNumeralFromChord(
...     chord.Chord(['C4', 'E-4', 'G4']),
...     key.Key('c'),
...     )
<music21.roman.RomanNumeral i in c minor>

>>> roman.romanNumeralFromChord(
...     chord.Chord(['E-3', 'C4', 'G-6']),
...     key.Key('g#'),
...     )
<music21.roman.RomanNumeral bivo6 in g# minor>

If no such keyObj is provided, this function will still run with a plausible key.
In most contexts, the guessed key corresponds to the chord:
the key's tonic is given by the chord's root, and
the key's quality (major or minor) comes from the (major or minor)
third between the chord's root and its third.

>>> roman.romanNumeralFromChord(
...     chord.Chord(['C4', 'E-4', 'G4']),
...     )  # NB: no key
<music21.roman.RomanNumeral i in c minor>

>>> roman.romanNumeralFromChord(
...     chord.Chord(['C4', 'E4', 'G4']),
...     )  # NB: no key and nor major third
<music21.roman.RomanNumeral I in C major>

For the special context of augmented sixths, however, this function
picks up on the different key suggested by that chord configuration:

>>> roman.romanNumeralFromChord(
...     chord.Chord('E-4 G4 C#5'),
...     )
<music21.roman.RomanNumeral It6 in g minor>

>>> roman.romanNumeralFromChord(
...     chord.Chord('E-4 G4 B-4 C#5'),
...     )
<music21.roman.RomanNumeral Ger65 in g minor>

>>> roman.romanNumeralFromChord(
...     chord.Chord('E-4 G4 A4 C#5'),
...     )
<music21.roman.RomanNumeral Fr43 in g minor>

>>> roman.romanNumeralFromChord(
...     chord.Chord('E-4 G4 A#4 C#5'),
...     )
<music21.roman.RomanNumeral Sw43 in g minor>

Naturally, the user can still specify a different key:

>>> roman.romanNumeralFromChord(
...     chord.Chord('E-4 G4 C#5'),
...     key.Key('G')
...     )
<music21.roman.RomanNumeral It6 in G major>

And if that key makes the chord no longer an augmented 6th chord
then the returned RomanNumeral will reflect this:

>>> roman.romanNumeralFromChord(
...     chord.Chord('E-4 G4 C#5'),
...     key.Key('C')
...     )
<music21.roman.RomanNumeral #io6b3 in C major>`

**Comment by MarkGotham** [comment] 2020-11-12 16:42
... followed by explicitly testing the 6th/7th in minor and perhaps removing some of the other stuff in there, especially the 'former bugs' which will hopefully be a distant memory by the end of all this.

**Comment by jacobtylerwalls** [comment] 2020-11-12 16:43
If comments won't do I suppose a collaborator could open a PR against someone else's fork/branch having the top-level PR against cuthbertLab. So yeah, I would say collaboration is a good formula for getting stuff done!

**Comment by jacobtylerwalls** [comment] 2020-11-12 16:47
That said I'm definitely a fan of small pull requests, I.e. anything that could get polished and merged separately should be separated.

**Comment by mscuthbert** [comment] 2020-11-12 20:46
I'm definitely a fan of small pull requests -- I can handle them anytime I sort through my email, which is about 4x per day.  Otherwise I have to look through all the code carefully, re-learn my existing code (harder if someone else wrote it at a time I wasn't making all contributions look like the existing code) to find a time to review when I have a block of time for "music21 work" in my schedule, and until the term is over, that's only a few times a month.

Definitely the improved docs would be a great and welcome PR in themselves.  AND they will ensure that I don't break anything in any other refactors.  They also will minimize the risk of time-wasting merge conflicts.

**Comment by MarkGotham** [comment] 2020-11-12 21:25
Thanks both. I'll put in some doc edits and basic clean up then to get the ball rolling.

**Closed** 2020-11-27 09:19 UTC
