### ISSUE TITLE
Anaconda package update

### ISSUE THREAD

**Issue by AngryMaciek** [cuthbertLab/music21#346] opened 2018-11-20 12:29 UTC
Dear Authors,
Would you please mind an update of the package @ the [anaconda repository](https://anaconda.org/mutirri/music21)? The version there is quite outdated and I would like to make a virtual environment with the current stable version.

Regards,

**Comment by andrewsanchez** [comment] 2018-11-26 20:53
@AngryMaciek You don't need that conda package to install the latest version of `music21` in a conda environment.  You can use `conda` and `pip` together.  
For example:
```
conda create -n music21 python=3.6
conda activate music21
pip install music21
```

**Comment by mscuthbert** [comment] 2018-11-26 21:31
And, that repository is not an official music21 repository in any way.

**Comment by AngryMaciek** [comment] 2018-12-20 19:43
Dear Authors,

Thanks for the good point! That is true, although I would like to create a snakemake pipeline for automatic data analysis using your package. Therefore I would need a repository at the anaconda cloud service, as snakemake rules would point there.

Is there a possibility you create an official music21 repository at the anaconda cloud?

**Comment by mscuthbert** [comment] 2018-12-20 20:17
Sorry that I don't know anything about the Anaconda cloud service and can't add another support item to my plate, but happy to give my endorsement to have the latest release on there at all times if someone who knows that system can do it.

**Comment by andrewsanchez** [comment] 2018-12-20 20:53
@AngryMaciek I'm almost certain that you don't need music21 to be conda installable to accomplish your goals with snakemake.  Is pinning the exact version of music21 your main concern?  I'm actually in the process of developing my first snakemake workflow as well as a conda package.  I may be able to help with building a conda package for music21 in the future.  It would be worth putting in the work to automate building and deploying a conda package as part of music21's CI.  Then it would be guaranteed to be in sync with the latest music21.  Then there could be an up to date music21 conda package that wouldn't require any extra effort from the music21 team to maintain.   But for now, maybe open another issue specifically regarding using snakemake with music21 and I can try to help with the workflow you want to develop.

**Comment by andrewsanchez** [comment] 2018-12-20 20:56
> Then it would be guaranteed to be in sync with the latest music21. Then there could be an up to date music21 conda package that wouldn't require any extra effort from the music21 team to maintain. 

Note that for this to happen, it might require @mscuthbert to approve configuring the CI pipeline to support auto building/deploying the conda package.    Would you be open to that @mscuthbert ?

**Comment by mscuthbert** [comment] 2018-12-20 22:21
@andrewsanchez -- sure; just update the .travis.yml as part of the pull request.  But I would doubt that many people would want the latest git repo -- could it be part of dist/dist.py and then get the latest release version?  I don't have the time to be able to debug something immediately if for some reason there's a regression on master -- the only thing that I'll drop other work to hotfix are crashing errors in releases.  Pinning to the latest master is highly likely to result in more instability than stability.

**Comment by iainsgillis** [comment] 2018-12-30 20:53
I've never used CI before, so updating the `.travis.yml` is beyond my current knowledge. A perusal of the [conda documentation](https://conda.io/docs/commands.html#conda-build-commands) led me to `conda skeleton`, `conda build`, and `conda convert -f all`. A one-line batch script yielded this:

https://anaconda.org/iainsgillis/music21

Definitely unofficial, but the tests that ran at the end of the `conda-build` process pass, and the locally built packages for `win-64` and `linux-64` installed without any trouble on my machine, as did those for `armv71` on my Raspberry Pi.

**Comment by andrewsanchez** [comment] 2018-12-30 22:53
Nice!  Since conda packages can include all kinds of other software, not just python, I think the real value in providing a conda package would be the ability to install an environment that includes a music XML reader and other dependencies to ensure other features like MIDI playback work out of the box.

**Comment by iainsgillis** [comment] 2019-06-15 18:18
Hi, Folks: As before, I can only speak to the successful installation of `win-64`, `linux-64`, and `armv71`, so YMMV (although I haven't received any notifications from any of 116 downloads in the past 5 months, which seems to suggest they're working everywhere).

I've updated https://anaconda.org/iainsgillis/music21 to v5.7. Python 3.7 is up; I'm building for Python 3.6 and 3.5 and will upload those later today.

**Comment by jacobtylerwalls** [comment] 2020-11-24 17:47
Hey errbody, I got this up on conda-forge:
https://anaconda.org/conda-forge/music21

Install should work with:
`conda install -c conda-forge music21`

And all that has to be done with each release is bump the version number and checksum (from PyPI) at this repo (`recipe/meta.yaml`):
https://github.com/conda-forge/music21-feedstock

@mscuthbert let's close this ticket, eh?

**Comment by mscuthbert** [comment] 2020-12-13 01:52
Thanks for taking this on @jacobtylerwalls !

**Closed by mscuthbert** 2020-12-13 01:52 UTC
