### ISSUE TITLE
Converting midi files failed in 32nd notes

### ISSUE THREAD

**Issue by Shoko-Makinohara** [cuthbertLab/music21#530] opened 2020-04-26 19:52 UTC
When I used converter.parse to load the midi file as below,
![image](https://user-images.githubusercontent.com/58494957/80318051-074a1e00-883a-11ea-8d50-733f62476a43.png)
The result was weird cause some durations could be 0:
![image](https://user-images.githubusercontent.com/58494957/80318086-3d879d80-883a-11ea-9352-89b62c34f71b.png)
Then I converted it back to midi file, it looked like
![image](https://user-images.githubusercontent.com/58494957/80318104-5e4ff300-883a-11ea-9be4-d5625f957211.png)
Don't know what happened...

**Comment by Shoko-Makinohara** [comment] 2020-04-26 19:56
The midi file could be downloaded [here](http://www.stringquartets.org/MIDIfiles/Haydn/HaydnSQ/HaydnSQ20n1/H20n1m1.squ) (you may modify .squ to .mid directly)
The bug is in the tenth bar of the second violon.

**Comment by Shoko-Makinohara** [comment] 2020-04-27 06:00
A stupid solution is to convert midi file to musicxml/mxl file, and then load it with converter.parse(). But it's kind of ugly when handling Metadata/Score/Part. 

`score= converter.parse(mxl_file_path)
note = score.measure(10).parts[1].measure(10)[2]`

**Comment by jacobtylerwalls** [comment] 2020-05-26 01:18
Midi import quantizes (rounds) to the nearest 16th by default:

https://github.com/cuthbertLab/music21/blob/2e1a8e7b6babca92ebc28ba1927f7184e0fcfa6a/music21/midi/translate.py#L1747

I was able to reproduce this with a minimal example containing 4 consecutive 32nd notes:

```s = converter.parse("../Desktop/4_32notes.mid")
s.show("text")
{0.0} <music21.stream.Part 0x11dd47fa0>
    {0.0} <music21.instrument.Piano 'Piano'>
    {0.0} <music21.tempo.MetronomeMark animato Quarter=120.0>
    {0.0} <music21.key.Key of C major>
    {0.0} <music21.meter.TimeSignature 4/4>
    {0.0} <music21.note.Note E>
    {0.0} <music21.note.Note E>
    {0.0} <music21.note.Rest rest>
    {0.25} <music21.note.Note E>
    {0.25} <music21.note.Rest rest>
    {0.3333} <music21.note.Note E>```

**Comment by jacobtylerwalls** [comment] 2020-05-26 01:20
Workaround:

Instead of calling converter.parse(), which does not allow you to pass a keyword argument for quarterLengthDivisors, call midi.translate.midiFilePathToStream with a keyword argument for 32nd division like this:

`s = midi.translate.midiFilePathToStream('4_32nds.mid', quarterLengthDivisors=[8])`

Hope this helps.

**Comment by jacobtylerwalls** [comment] 2020-05-26 01:40
Actually, there's an idea for a PR. 

converter.parse() accepts **keywords and passes them onward, so the breakdown is actually here:


https://github.com/cuthbertLab/music21/blob/f65327fae4a8064743d2776fc32a49f9d39f2bf7/music21/converter/__init__.py#L608

I'll open a PR for adding **keywords here, which I see does allow calling convert.parse('32.mid', quantizePost=False)

**Comment by jacobtylerwalls** [comment] 2020-05-26 01:54
Shut my mouth. You can use keywords in converter.parse() and have them carry through. I must have had stale variables somewhere. 

OP, why don't you let use know if you can call convert.parse('your_file.mid', quantizePost=False) and get your expected result.

**Comment by jacobtylerwalls** [comment] 2020-05-28 00:23
Hint: you will want to set forceSource=True since the file has already been processed once on your system and it will just read the unwanted result back from disk.

Try:
`converter.parse('your_file.mid', forceSource=True, quantizePost=False)`

Or, rename the file?

**Comment by mscuthbert** [comment] 2020-06-01 16:57
Clearly the rest of the keywords assigned to converter.parse need to be part of the hashing algorithm for determining whether to read from disk or not;  will make a todo when I’m back on internet (replying offline now)

Best,
Michael

---
Sent from a phone (413-575-6024)
Apologies for typos or general brevity

On May 27, 2020, at 20:23, Jacob Walls <notifications@github.com> wrote:

﻿

Hint: you will want to set forceSource=True since the file has already been processed once on your system and it will just read the unwanted result back from disk.

Try:
converter.parse('your_file.mid', forceSource=True, quantizePost=False)

Or, rename the file?

**Closed** 2020-09-28 22:50 UTC
