### ISSUE TITLE
Export of RepeatBrackets to MusicXML get messed up by joinPartStaffs

### ISSUE THREAD

**Issue by gregchapman-dev** [cuthbertLab/music21#1380] opened 2022-08-15 01:02 UTC
**music21 version**

`7.2 (and 8.0)`   

**Problem summary**

Left barline <ending> gets deleted during joinPartStaffs.

It's _possible_ that the triggering factor is something weird I'm doing as I add support for RepeatBrackets to my humdrum parser.  I'll work on putting together a simple example to rule that out.

**Comment by jacobtylerwalls** [comment] 2022-09-10 14:29
Thanks @gregchapman-dev I'm going to close this as a duplicate of #1380, feel free to reopen if you find other failures after the fix.

**Closed by jacobtylerwalls** 2022-09-10 14:29 UTC
