### ISSUE TITLE
Incorrect midi for ties

### ISSUE THREAD

**Issue by AlmogCohen** [cuthbertLab/music21#514] opened 2020-02-04 12:29 UTC
Hi! Using the a fresh music21 installation from PyPi I find that midi is generated incorrectly for ties.

Please see this example:
```
    s1 = stream.Stream()

    n = note.Note("C4", quarterLength=1.0)
    n.tie = tie.Tie("start")

    n2 = note.Note("C4", quarterLength=1.0)
    n2.tie = tie.Tie("stop")

    n3 = note.Note("C4", quarterLength=1.0)
    n4 = note.Note("C4", quarterLength=1.0)


    s1.append(n)
    s1.append(n2)
    s1.append(n3)
    s1.append(n4)

    # s1.show()
    s1.show('midi')
```

The output midi is incorrect and all notes are played one-by-one as quarters. This is how the midi looks like in MuseScore: ![WhatsApp Image 2020-02-04 at 14 16 13](https://user-images.githubusercontent.com/3888998/73744786-329cff80-475a-11ea-946f-9529e6473d25.jpeg)

This is how the output looks like in LogicX: ![WhatsApp Image 2020-02-04 at 14 16 36](https://user-images.githubusercontent.com/3888998/73744809-434d7580-475a-11ea-9aef-28b143a2b2f3.jpeg)

**NOTE:** In the LogicX output I've shifted the first note up so you could see how they overlap. Originally all notes are C. In the LogicX output it seems like the first note is indeed generated with the tie, but the second one is generated as well while it shouldn't!

What do you think guys? Thanks in advance!

**Comment by mscuthbert** [comment] 2020-02-05 17:58
Does the same problem happen if the tie's not on the first two notes of the piece?  We've had problems with initial notes and just want to be sure on that.

On the one hand -- I can't possibly believe that something as fundamental as Ties has been broken in music21 MIDI for over a decade!  On the other hand -- I can't remember seeing any tests or code about ties in MIDI...

**Comment by mscuthbert** [comment] 2020-02-05 18:00
Looking more closely `midi.translate.streamHierarchyToMidiTracks` runs stripTies.  Would you be able to save me some time and seeing what the midi.MidiTracks objects emitted by that method looks like from your stream?  Thanks!

**Comment by jacobtylerwalls** [comment] 2020-05-25 23:34
I'll gladly chime in with the output:

>>> midi.translate.streamHierarchyToMidiTracks(s1)
[<MidiTrack 1 -- 22 events
    <MidiEvent DeltaTime, t=0, track=1, channel=1>
    <MidiEvent SEQUENCE_TRACK_NAME, t=0, track=1, channel=1, data=b''>
    <MidiEvent DeltaTime, t=0, track=1, channel=1>
    <MidiEvent PITCH_BEND, t=0, track=1, channel=1, parameter1=0, parameter2=64>
    <MidiEvent DeltaTime, t=0, track=1, channel=1>
    **<MidiEvent NOTE_ON, t=0, track=1, channel=1, pitch=60, velocity=90>
    <MidiEvent DeltaTime, t=1024, track=1, channel=1>
    <MidiEvent NOTE_ON, t=0, track=1, channel=1, pitch=60, velocity=90>
    <MidiEvent DeltaTime, t=1024, track=1, channel=1>
    <MidiEvent NOTE_OFF, t=0, track=1, channel=1, pitch=60, velocity=0>
    <MidiEvent DeltaTime, t=0, track=1, channel=1>
    <MidiEvent NOTE_OFF, t=0, track=1, channel=1, pitch=60, velocity=0>
    <MidiEvent DeltaTime, t=0, track=1, channel=1>**
    <MidiEvent NOTE_ON, t=0, track=1, channel=1, pitch=60, velocity=90>
    <MidiEvent DeltaTime, t=1024, track=1, channel=1>
    <MidiEvent NOTE_OFF, t=0, track=1, channel=1, pitch=60, velocity=0>
    <MidiEvent DeltaTime, t=0, track=1, channel=1>
    <MidiEvent NOTE_ON, t=0, track=1, channel=1, pitch=60, velocity=90>
    <MidiEvent DeltaTime, t=1024, track=1, channel=1>
    <MidiEvent NOTE_OFF, t=0, track=1, channel=1, pitch=60, velocity=0>
    <MidiEvent DeltaTime, t=1024, track=1, channel=1>
    <MidiEvent END_OF_TRACK, t=None, track=1, channel=1, data=b''>
  >]


And it does not appear to be any different when the tie occurs midmeasure: here is the a stream constructed using the original example in the order n3, n, n2, n4:

>>> midi.translate.streamHierarchyToMidiTracks(s2)
[<MidiTrack 1 -- 22 events
    <MidiEvent DeltaTime, t=0, track=1, channel=1>
    <MidiEvent SEQUENCE_TRACK_NAME, t=0, track=1, channel=1, data=b''>
    <MidiEvent DeltaTime, t=0, track=1, channel=1>
    <MidiEvent PITCH_BEND, t=0, track=1, channel=1, parameter1=0, parameter2=64>
    <MidiEvent DeltaTime, t=0, track=1, channel=1>
    <MidiEvent NOTE_ON, t=0, track=1, channel=1, pitch=60, velocity=90>
    <MidiEvent DeltaTime, t=1024, track=1, channel=1>
    <MidiEvent NOTE_OFF, t=0, track=1, channel=1, pitch=60, velocity=0>
    <MidiEvent DeltaTime, t=0, track=1, channel=1>
    **<MidiEvent NOTE_ON, t=0, track=1, channel=1, pitch=60, velocity=90>
    <MidiEvent DeltaTime, t=1024, track=1, channel=1>
    <MidiEvent NOTE_ON, t=0, track=1, channel=1, pitch=60, velocity=90>
    <MidiEvent DeltaTime, t=1024, track=1, channel=1>
    <MidiEvent NOTE_OFF, t=0, track=1, channel=1, pitch=60, velocity=0>
    <MidiEvent DeltaTime, t=0, track=1, channel=1>
    <MidiEvent NOTE_OFF, t=0, track=1, channel=1, pitch=60, velocity=0>
    <MidiEvent DeltaTime, t=0, track=1, channel=1>**
    <MidiEvent NOTE_ON, t=0, track=1, channel=1, pitch=60, velocity=90>
    <MidiEvent DeltaTime, t=1024, track=1, channel=1>
    <MidiEvent NOTE_OFF, t=0, track=1, channel=1, pitch=60, velocity=0>
    <MidiEvent DeltaTime, t=1024, track=1, channel=1>
    <MidiEvent END_OF_TRACK, t=None, track=1, channel=1, data=b''>
  >]

**Comment by jacobtylerwalls** [comment] 2020-06-20 15:37
Likely duplicate of #266

**Closed** 2020-07-23 15:15 UTC
